"""
This type stub file was generated by pyright.
"""

from typing import Optional, TYPE_CHECKING
from hyper import HTTP20Connection
from hyper.ssl_compat import SSLContext

if TYPE_CHECKING:
    ...
DEFAULT_TOKEN_LIFETIME = ...
DEFAULT_TOKEN_ENCRYPTION_ALGORITHM = ...
class Credentials:
    def __init__(self, ssl_context: Optional[SSLContext] = ...) -> None:
        ...
    
    def create_connection(self, server: str, port: int, proto: Optional[str], proxy_host: Optional[str] = ..., proxy_port: Optional[int] = ...) -> HTTP20Connection:
        ...
    
    def get_authorization_header(self, topic: Optional[str]) -> Optional[str]:
        ...
    


class CertificateCredentials(Credentials):
    def __init__(self, cert_file: Optional[str] = ..., password: Optional[str] = ..., cert_chain: Optional[str] = ...) -> None:
        ...
    


class TokenCredentials(Credentials):
    def __init__(self, auth_key_path: str, auth_key_id: str, team_id: str, encryption_algorithm: str = ..., token_lifetime: int = ...) -> None:
        ...
    
    def get_authorization_header(self, topic: Optional[str]) -> str:
        ...
    


