"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Iterable, List, Optional, Union

MAX_PAYLOAD_SIZE = ...
class PayloadAlert:
    def __init__(self, title: Optional[str] = ..., title_localized_key: Optional[str] = ..., title_localized_args: Optional[List[str]] = ..., body: Optional[str] = ..., body_localized_key: Optional[str] = ..., body_localized_args: Optional[List[str]] = ..., action_localized_key: Optional[str] = ..., action: Optional[str] = ..., launch_image: Optional[str] = ...) -> None:
        ...
    
    def dict(self) -> Dict[str, Any]:
        ...
    


class Payload:
    def __init__(self, alert: Union[PayloadAlert, str, None] = ..., badge: Optional[int] = ..., sound: Optional[str] = ..., category: Optional[str] = ..., url_args: Optional[Iterable[str]] = ..., custom: Optional[Dict[str, Any]] = ..., thread_id: Optional[str] = ..., content_available: bool = ..., mutable_content: bool = ...) -> None:
        ...
    
    def dict(self) -> Dict[str, Any]:
        ...
    


