services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: never
    volumes:
      - ./:/app
      - insightface_cache:/root/.insightface

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: never

  email-worker:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: never
    volumes:
      - ./:/app

volumes:
  insightface_cache:
