"""
This type stub file was generated by pyright.
"""

import asyncio
import base64
import json
import os
import time
import logging
import aiohttp
import http_ece
import requests
from copy import deepcopy
from typing import Dict, Union, cast
from urlparse import urlparse
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import serialization
from functools import partial
from py_vapid import Vapid, Vapid01
from requests import Response

class WebPushException(Exception):
    """Web Push failure.

    This may contain the requests.Response

    """
    def __init__(self, message, response=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class NoData(Exception):
    """Message contained No Data, no encoding required."""
    ...


class CaseInsensitiveDict(dict):
    """A dictionary that has case-insensitive keys"""
    def __init__(self, data=..., **kwargs) -> None:
        ...
    
    def __contains__(self, key) -> bool:
        ...
    
    def __setitem__(self, key, value): # -> None:
        ...
    
    def __getitem__(self, key):
        ...
    
    def __delitem__(self, key): # -> None:
        ...
    
    def get(self, key, default=...): # -> None:
        ...
    
    def update(self, data) -> None:
        ...
    


class WebPusher:
    """WebPusher encrypts a data block using HTTP Encrypted Content Encoding
    for WebPush.

    See https://tools.ietf.org/html/draft-ietf-webpush-protocol-04
    for the current specification, and
    https://developer.mozilla.org/en-US/docs/Web/API/Push_API for an
    overview of Web Push.

    Example of use:

    The javascript promise handler for PushManager.subscribe()
    receives a subscription_info object. subscription_info.getJSON()
    will return a JSON representation.
    (e.g.
    .. code-block:: javascript
        subscription_info.getJSON() ==
        {"endpoint": "https://push.server.com/...",
         "keys":{"auth": "...", "p256dh": "..."}
        }
    )

    This subscription_info block can be stored.

    To send a subscription update:

    .. code-block:: python
        # Optional
        # headers = py_vapid.sign({"aud": "https://push.server.com/",
                                   "sub": "mailto:your_admin@your.site.com"})
        data = "Mary had a little lamb, with a nice mint jelly"
        WebPusher(subscription_info).send(data, headers)

    """
    subscription_info = ...
    valid_encodings = ...
    verbose = ...
    def __init__(self, subscription_info: Dict[str, Union[Union[str, bytes], Dict[str, Union[str, bytes]]]], requests_session: Union[None, requests.Session] = ..., aiohttp_session: Union[None, aiohttp.client.ClientSession] = ..., verbose: bool = ...) -> None:
        """Initialize using the info provided by the client PushSubscription
        object (See
        https://developer.mozilla.org/en-US/docs/Web/API/PushManager/subscribe)

        :param subscription_info: a dict containing the subscription_info from
            the client.
        :type subscription_info: dict

        :param requests_session: a requests.Session object to optimize requests
            to the same client.
        :type requests_session: requests.Session

        :param verbose: provide verbose feedback
        :type verbose: bool

        """
        ...
    
    def verb(self, msg: str, *args, **kwargs) -> None:
        ...
    
    def encode(self, data: bytes, content_encoding: str = ...) -> CaseInsensitiveDict:
        """Encrypt the data.

        :param data: A serialized block of byte data (String, JSON, bit array,
            etc.) Make sure that whatever you send, your client knows how
            to understand it.
        :type data: str
        :param content_encoding: The content_encoding type to use to encrypt
            the data. Defaults to RFC8188 "aes128gcm". The previous draft-01 is
            "aesgcm", however this format is now deprecated.
        :type content_encoding: enum("aesgcm", "aes128gcm")

        """
        ...
    
    def as_curl(self, endpoint: str, encoded_data: bytes, headers: Dict[str, str]) -> str:
        """Return the send as a curl command.

        Useful for debugging. This will write out the encoded data to a local
        file named `encrypted.data`

        :param endpoint: Push service endpoint URL
        :type endpoint: basestring
        :param encoded_data: byte array of encoded data
        :type encoded_data: bytearray
        :param headers: Additional headers for the send
        :type headers: dict
        :returns string

        """
        ...
    
    def send(self, *args, **kwargs) -> Union[Response, str]:
        """Encode and send the data to the Push Service"""
        ...
    
    async def send_async(self, *args, **kwargs) -> Union[aiohttp.ClientResponse, str]:
        ...
    


def webpush(subscription_info: Dict[str, Union[Union[str, bytes], Dict[str, Union[str, bytes]]]], data: Union[None, str] = ..., vapid_private_key: Union[None, Vapid, str] = ..., vapid_claims: Union[None, Dict[str, Union[str, int]]] = ..., content_encoding: str = ..., curl: bool = ..., timeout: Union[None, float] = ..., ttl: int = ..., verbose: bool = ..., headers: Union[None, Dict[str, Union[str, int, float]]] = ..., requests_session: Union[None, requests.Session] = ...) -> Union[str, requests.Response]:
    """
        One call solution to endcode and send `data` to the endpoint
        contained in `subscription_info` using optional VAPID auth headers.

        in example:

        .. code-block:: python

        from pywebpush import python

        webpush(
            subscription_info={
                "endpoint": "https://push.example.com/v1/abcd",
                "keys": {"p256dh": "0123abcd...",
                         "auth": "001122..."}
                 },
            data="Mary had a little lamb, with a nice mint jelly",
            vapid_private_key="path/to/key.pem",
            vapid_claims={"sub": "YourNameHere@example.com"}
            )

        No additional method call is required. Any non-success will throw a
        `WebPushException`.

    :param subscription_info: Provided by the client call
    :type subscription_info: dict
    :param data: Serialized data to send
    :type data: str
    :param vapid_private_key: Vapid instance or path to vapid private key PEM \
                              or encoded str
    :type vapid_private_key: Union[Vapid, str]
    :param vapid_claims: Dictionary of claims ('sub' required)
    :type vapid_claims: dict
    :param content_encoding: Optional content type string
    :type content_encoding: str
    :param curl: Return as "curl" string instead of sending
    :type curl: bool
    :param timeout: POST requests timeout
    :type timeout: float
    :param ttl: Time To Live
    :type ttl: int
    :param verbose: Provide verbose feedback
    :type verbose: bool
    :return requests.Response or string
    :param headers: Dictionary of extra HTTP headers to include
    :type headers: dict

    """
    ...

async def webpush_async(subscription_info: Dict[str, Union[Union[str, bytes], Dict[str, Union[str, bytes]]]], data: Union[None, str] = ..., vapid_private_key: Union[None, Vapid, str] = ..., vapid_claims: Union[None, Dict[str, Union[str, int]]] = ..., content_encoding: str = ..., curl: bool = ..., timeout: Union[None, float] = ..., ttl: int = ..., verbose: bool = ..., headers: Union[None, Dict[str, Union[str, int, float]]] = ..., aiohttp_session: Union[None, aiohttp.ClientSession] = ...) -> Union[str, aiohttp.ClientResponse]:
    """
        Async version of webpush function. One call solution to encode and send 
        `data` to the endpoint contained in `subscription_info` using optional 
        VAPID auth headers.

        Example:

        .. code-block:: python

        from pywebpush import webpush_async
        import asyncio

        async def send_notification():
            response = await webpush_async(
                subscription_info={
                    "endpoint": "https://push.example.com/v1/abcd",
                    "keys": {"p256dh": "0123abcd...",
                             "auth": "001122..."}
                     },
                data="Mary had a little lamb, with a nice mint jelly",
                vapid_private_key="path/to/key.pem",
                vapid_claims={"sub": "YourNameHere@example.com"}
                )

        asyncio.run(send_notification())

        No additional method call is required. Any non-success will throw a
        `WebPushException`.

    :param subscription_info: Provided by the client call
    :type subscription_info: dict
    :param data: Serialized data to send
    :type data: str
    :param vapid_private_key: Vapid instance or path to vapid private key PEM \
                              or encoded str
    :type vapid_private_key: Union[Vapid, str]
    :param vapid_claims: Dictionary of claims ('sub' required)
    :type vapid_claims: dict
    :param content_encoding: Optional content type string
    :type content_encoding: str
    :param curl: Return as "curl" string instead of sending
    :type curl: bool
    :param timeout: POST requests timeout
    :type timeout: float
    :param ttl: Time To Live
    :type ttl: int
    :param verbose: Provide verbose feedback
    :type verbose: bool
    :param headers: Dictionary of extra HTTP headers to include
    :type headers: dict
    :param aiohttp_session: Optional aiohttp ClientSession for connection reuse
    :type aiohttp_session: aiohttp.ClientSession
    :return aiohttp.ClientResponse or string

    """
    ...

